name: oss_dart
description: A dart package project can use Alibaba cloud OSS service
version: 0.1.0
author: caipeng<caipenghsxr@gmail.com>
homepage: https://github.com/caipeng-hrv/oss_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1 #计算文件的哈希
  intl: ^0.17.0 # ^0.16.1
  http: ^0.13.3
  xml2json: ^5.3.1
  # dio: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

