name: lianmisdk
description: Demonstrates how to use the linkme_flutter_sdk plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1 #文件路径
  event_bus: ^2.0.0
  logger: ^1.0.0
  linkme_flutter_sdk:
    path: ../

  cupertino_icons: ^1.0.0
  # permission_handler: ^5.0.1+1 #权限
  permission_handler: ^8.1.1
  image_picker: ^0.7.3
  provider: ^5.0.0
  city_pickers: ^1.0.1
  image_gallery_saver: ^1.6.9 #图片保存到相册
  photo_view: ^0.12.0 #图片页
  flutter_svg: ^0.21.0-nullsafety.0
  file_picker:  #多种格式文件选择器,由于 android/build.gradle文件的版本不对，所有暂时classpath 'com.android.tools.build:gradle:4.0.1'
    path: ../../file_picker

  oss_dart:
    path: ../../oss_dart

  flutter_pdfview: ^1.1.0 #pdf文件预览

dev_dependencies:
  flutter_test:
    
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
    - assets/neat.gif
    - assets/large-image.jpg
    - assets/small-image.jpg
    - assets/gallery1.jpg
    - assets/gallery2.jpg
    - assets/gallery3.jpg
    - assets/firefox.svg
    
    - assets/images/
    
    # pdf
    - assets/pdf/demo.pdf
    - assets/pdf/corrupted.pdf
    - assets/pdf/demo-link.pdf
    - assets/pdf/demo-landscape.pdf

    - packages/flutter_gallery_assets/people/ali_landscape.png
    - packages/flutter_gallery_assets/people/square/ali.png
    - packages/flutter_gallery_assets/people/square/peter.png
    - packages/flutter_gallery_assets/people/square/sandra.png
    - packages/flutter_gallery_assets/people/square/stella.png
    - packages/flutter_gallery_assets/people/square/trevor.png
    - packages/flutter_gallery_assets/places/india_tanjore_bronze_works.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_merchant.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple_carvings.png
  fonts:
    - family: PTSans
      fonts:
        - asset: assets/fonts/ptasans-regular.ttf
        - asset: assets/fonts/ptasans-bold.ttf
          weight: 700
